### ISSUE TITLE
assert_all_payloads_succeeded testing helper

### ISSUE THREAD

**Issue by awichmann-mintel** [mintel/lpipe#21]
I apologize if I've asked for this before, but I've added this helper to 2 projects now. Can we add it to the testing utils?

```python
def assert_all_payloads_succeeded(response):
    assert response["stats"]["received"] == response["stats"]["successes"]
    assert response["event"] == "Finished."
```

**Comment by alphachai** [comment]
The first assertion means you’re not checking that the correct number of messages were even received. On the other, the message “Finished” is not guaranteed, it’s more of a log message. Testing against log messages is...inadvisable.
