### ISSUE TITLE
Proposal for API to parse event

### ISSUE THREAD

**Issue by xiang-zhu** [mintel/lpipe#25]
We like a lot of features provided from this library, however found the directed graph workflow and the API enforced from it not fit with our use case.

Is it possible to provide an API to process lambda events, without enforce calling `lpipe.process_event` and pass in call back function?

The interface could look like

`parse_event(event_type:str, message_type:str=None) -> Generator[dict, None, None]`

`event_type` mapt to the event source mapping type, coiuld be sqs/sns/dynamodb/kinisis/cloudwatch etc.
`message_type` as optional argument for parsing specific format of message, like bucket notification
and return a generator that yield each parsed event message as dict

An interface like this will lower the boundary of adopting the library by a lot, let me know what's your thought.

**Comment by alphachai** [comment]
I think this might make sense to add. While I’d still prefer everyone use `process_event`, this proposed function would simplify some elements of the core loop, and may make sense to add regardless. I’ll experiment with this next week. 👍
